### ISSUE TITLE
SECURITY: Whitelist/Blackilist columns

### ISSUE THREAD

**Issue by ghost** [freshbitsweb/laratables#26]
Hi
Thank you for the package.
Cause of security issues we need to be able to define "whitelist" and "blacklist" columns, so these columns won't be searchable or orderable.

**Comment by gauravmak** [comment]
Added the option to specify `non_searchable_columns` with the new release.

Orderable columns are decided on the client side and Datatables instructs the server to order the records based on user selection so that option is not currently feasible. Thanks.

**Comment by ghost** [comment]
@gauravmak It wasn't only for search, you had to add it for both order and search, also I think calling it `whitelist` or `blacklist` would be better and useful for both search and order.

**Comment by gauravmak** [comment]
As I said, limiting orderable columns is not in the control of server side as client side configuration is specified by developer directly.

And preventing sorting of a column after it's selected by user is not good for User experience.

Ordering is something you will need to manage yourself for now. Thanks

**Comment by ghost** [comment]
@gauravmak It seems you've miss-understanded me, go and check `yajra/laravel-datatable` it has whitelist and blcklist for both search and order.
The hacker can edit the Ajax request and specify the columns for order that we don't want.
Anyways I am creating new lib using your library.

**Comment by gauravmak** [comment]
Yes, Yajra's package can provide the option because they also control the client side code.

But here, to enable this feature, we have to break the rule and try controlling the client side code which would break the policy of keeping this package developer friendly.

Happy to know that this package will help you create a new one. All the best and let me know if I can help in any way. Thanks.
