### ISSUE TITLE
Possible to search custom column

### ISSUE THREAD

**Issue by keithsk** [freshbitsweb/laratables#68]
Dear Sir,

I have one custom column (status) which not in database, and the value is custom value that i set based on some condition, is it possible to search this custom column value by "CLOSED" / "OPEN"? Or have any other alternative to done it, appreciated for advice.

```
public static function laratablesCustomStatus($value)
{
        if($value->closed == 1) {
               return 'CLOSED';
        } else {
               return 'OPEN';
        }       
}
```

**Comment by gauravmak** [comment]
@keithsk If we allow searching on custom columns after the data is fetched already, the Datatables count may have a mismatch. We need to tell the Datatable about the number of total records that match the filter condition so that it can display the pagination. And we cannot decide that count if we allow filtration on a custom column which doesn't exist in the database.

The solution for you is to either:

1) Add the column in the database. You may store the column value as a boolean in the table and use [Custom search](https://github.com/freshbitsweb/laratables#searching) feature or

2) If there are no lots of records in the table, use Datatable directly without server-side processing (ajax).

**Comment by keithsk** [comment]
thank you very much @gauravmak
